# Generated by Django 4.2.2 on 2023-06-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='residence',
            new_name='resident',
        ),
    ]
